Add CLI support through `python -mbracex`
facelessuser/bracex pull request #29
Opened 2021-10-05 20:31 UTC by moreati

fixes #27

TODO
- [x] Changelog
- [x] Performance test
- [x] Consider parametrised unit tests
- [x] Consider a (default) strict mode (e.g. should an expression with no expansions be considered an error?)

2021-10-05 20:42 UTC, moreati commented
I dropped `--separator` in favour of `--terminator` and `-0` because
- having a terminator is more consistent with the behaviour of `find -print` or `find -print0`
- It's very hard or not possible to pass a NUL character as a string argument in bash.

Further discussion/background https://twitter.com/moreati/status/1443321003606745103

2021-10-05 20:53 UTC, facelessuser commented on docs/src/dictionary/en-custom.txt
> +nocover
These are normally needed. They should be ignored automatically due to the PySpelling config.

2021-10-05 20:54 UTC, facelessuser commented on docs/src/dictionary/en-custom.txt
> +nocover
To clarify, both `nocover` and `pragma` will be ignored.

2021-10-05 21:32 UTC, facelessuser commented on docs/src/dictionary/en-custom.txt
> +nocover
```console
➜  bracex git:(master) python3 -m pyspelling -n python
Spelling check passed :)
```

Notice I already have `# pragma: no cover` in source: https://github.com/facelessuser/bracex/blob/master/bracex/__meta__.py#L134

2021-10-05 21:35 UTC, facelessuser commented on docs/src/dictionary/en-custom.txt
> +nocover
Use `# pragma: no cover`. That's why it failed.

2021-10-13 00:20 UTC, facelessuser requested changes
Overall, it looks good! I've added a few comments on things that should be addressed.

2021-10-13 00:20 UTC, facelessuser commented on tests/test_main.py
> +
Please remove the extra new line.

2021-10-13 00:20 UTC, facelessuser commented on docs/src/markdown/about/changelog.md
> +- **NEW** Command line interface using `python3 -m bracex`
I just noticed this. To be consistent, can we add the colon after: `**NEW**:`?

2021-10-13 00:20 UTC, facelessuser commented on bracex/__main__.py
> +        description=__doc__.lstrip('\n').split('\n')[0],
While clever, I'd prefer we just copy the string here. It's a lot of work to get a single short string 🙂. It'll also be easier for people to understand in general.

2021-10-13 16:56 UTC, facelessuser commented on README.md
> +Copyright (c) 2021 Alex Willmer
Yeah, it caught me off guard, but no worries 🙂.

2021-10-13 18:12 UTC, facelessuser commented
I'll probably give it a little spin in the next few days and release this weekend.

2021-10-13 18:12 UTC, merged